# Default values for social-progressia-one.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

replicaCount: 1

image:
  registry: registry.digitalocean.com
  repository: progressiaone/social.progressia.one
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"
  # Set to true if you want to debug the container startup
  debug: false

# Image pull secrets for private registries
# Will use global.imagePullSecrets if not specified
imagePullSecrets:
  - name: progressiaone

# Override chart name and fullname
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automount the service account token
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "default"

# Pod annotations
podAnnotations: {}
  # Example: to force pod restart during deployments
  # redeployedAt: "2025-09-23T03:14:22Z"

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534  # nobody user
  runAsGroup: 65534
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8100
  annotations: {}
  # sessionAffinity: None
  # sessionAffinityConfig: {}


ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: social.progressia.one
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: social-progressia-one-tls
      hosts:
        - social.progressia.one

# Resource configuration for bskyweb container
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# bskyweb specific configuration
bskyweb:
  # Command line arguments for bskyweb
  args:
    - "/usr/bin/bskyweb"
    - "serve"
    - "--appview-host=https://public.api.bsky.app"
  
  # Environment variables
  env: []
    # - name: EXAMPLE_VAR
    #   value: "example_value"
    # - name: LOG_LEVEL
    #   value: "info"
  
  # Configuration from ConfigMap or Secret
  envFrom: []
    # - configMapRef:
    #     name: bskyweb-config
    # - secretRef:
    #     name: bskyweb-secrets
  
  # Port that bskyweb listens on
  port: 8100
  
  # Health check configuration
  healthCheck:
    enabled: true
    path: "/"
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  
  # Readiness probe configuration
  readinessProbe:
    enabled: true
    path: "/"
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
